// Language
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
// PERSMISSIONS
export const SET_PERMISSION = 'SET_PERMISSION';

// Loader
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// ERROR
export const ENABLE_ERROR = 'ENABLE_ERROR';
export const DISABLE_ERROR = 'DISABLE_ERROR';

// Contacts
export const SET_CONTACTS = 'SET_CONTACTS';
export const GET_CONTACTS = 'GET_CONTACTS';

// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_RESPONSE = 'FETCH_POSTS_RESPONSE';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

// FRIENDS
export const MAKE_FRIEND_REQUEST = 'MAKE_FRIEND_REQUEST';
export const MAKE_FRIEND_RESPONSE = 'MAKE_FRIEND_RESPONSE';
export const MAKE_FRIEND_FAILURE = 'MAKE_FRIEND_FAILURE';
export const ENABLE_LOADER_FRIENDS = 'ENABLE_LOADER_FRIENDS';
export const DISABLE_LOADER_FRIENDS = 'DISABLE_LOADER_FRIENDS';

// Map
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const SET_MAP_STYLE = 'SET_MAP_STYLE';
