// Language
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
// PERSMISSIONS
export const SET_PERMISSION = 'SET_PERMISSION';

// Loader
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// ERROR
export const ENABLE_ERROR = 'ENABLE_ERROR';
export const DISABLE_ERROR = 'DISABLE_ERROR';

// Contacts
export const SET_CONTACTS = 'SET_CONTACTS';
export const GET_CONTACTS = 'GET_CONTACTS';

// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_RESPONSE = 'FETCH_POSTS_RESPONSE';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
